// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type InsertOrderInfoReq struct {
	GoodsName string  `json:"goodsName"` //商品名称
	Price     float64 `json:"price"`     //商品名称
}

type OrderInfoReq struct {
	OrderId int64 `form:"orderId,optional"`
}

type OrderInfoResp struct {
	OrderId   int64  `json:"orderId"`   //订单id
	GoodsName string `json:"goodsName"` //商品名称
}
