// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: coupon.proto

package server

import (
	"context"

	"grpc_coupon/grpc/coupon"
	"grpc_coupon/internal/logic"
	"grpc_coupon/internal/svc"
)

type GrpcCouponServiceServer struct {
	svcCtx *svc.ServiceContext
	coupon.UnimplementedGrpcCouponServiceServer
}

func NewGrpcCouponServiceServer(svcCtx *svc.ServiceContext) *GrpcCouponServiceServer {
	return &GrpcCouponServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GrpcCouponServiceServer) GrpcGetCoupon(ctx context.Context, in *coupon.GrpcGetCouponReq) (*coupon.GrpcGetCouponResp, error) {
	l := logic.NewGrpcGetCouponLogic(ctx, s.svcCtx)
	return l.GrpcGetCoupon(in)
}
