info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登录接口
      parameters:
      - description: 登录用户名
        in: path
        name: username
        required: true
        type: string
      - description: 登录密码
        in: path
        name: passwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
swagger: "2.0"
