// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: anonymous_user.proto

package server

import (
	"context"

	"grpc_user/grpc/user"
	"grpc_user/internal/logic"
	"grpc_user/internal/svc"
)

type GrpcUserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedGrpcUserServiceServer
}

func NewGrpcUserServiceServer(svcCtx *svc.ServiceContext) *GrpcUserServiceServer {
	return &GrpcUserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GrpcUserServiceServer) GrpcGetUser(ctx context.Context, in *user.GrpcGetUserReq) (*user.GrpcGetUserResp, error) {
	l := logic.NewGrpcGetUserLogic(ctx, s.svcCtx)
	return l.GrpcGetUser(in)
}
