// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_zero_15_rabbitmq/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// http://127.0.0.1:8888/rabbitmq/api?msg=msg123456890011
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/rabbitmq/api",
				Handler: RabbitmqApiHandler(serverCtx),
			},
			{
				// http://127.0.0.1:8888/rabbitmq/api/simple?msg=msg123456890011
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/rabbitmq/api/simple",
				Handler: RabbitmqApiSimpleHandler(serverCtx),
			},
			{
				// http://127.0.0.1:8888/rabbitmq/api/publish?msg=msg123456890011
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/rabbitmq/api/publish",
				Handler: RabbitmqApiPublishHandler(serverCtx),
			},
			{
				// http://127.0.0.1:8888/rabbitmq/api/router?msg=msg123456890011
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/rabbitmq/api/router",
				Handler: RabbitmqApiRouterHandler(serverCtx),
			},
			{
				// http://127.0.0.1:8888/rabbitmq/api/topic?msg=msg123456890011
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/rabbitmq/api/topic",
				Handler: RabbitmqApiTopicHandler(serverCtx),
			},
			{
				// http://127.0.0.1:8888/rabbitmq/api/rpc?msg=msg123456890011
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/rabbitmq/api/rpc",
				Handler: RabbitmqApiRPCHandler(serverCtx),
			},
		},
	)
}
