version: '3.8'

services:
#  openresty:
#    image: openresty/openresty:alpine
#    container_name: cdn-gateway2
#    ports:
#      - "80:80"
#    volumes:
#      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
#      - ./lua:/usr/local/openresty/nginx/lua
#      - ./logs:/usr/local/openresty/nginx/logs
#    depends_on:
#      - backend
#    networks:
#      - cdn-network
#    restart: unless-stopped

  tavern:
    build: ./backend
    container_name: tavern
    ports:
      - "8080:8080"
    networks:
      - cdn-network
    restart: unless-stopped

networks:
  cdn-network:
    driver: bridge
