apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-kubectl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-kubectl
  template:
    metadata:
      labels:
        app: gin-kubectl
    spec:
      containers:
        - name: gin-kubectl
          image: gin-kubectl:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: gin-kubectl-service
spec:
  type: NodePort
  selector:
    app: gin-kubectl
  ports:
    - port: 18080
      targetPort: 18080
      nodePort: 30080
