// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DelayQueueRedisReq struct {
	Queue    string `form:"queue,optional"`
	Router   string `form:"router,optional"`
	Exchange string `form:"exchange,optional"`
	Msg      string `form:"msg,optional"`
}

type DelayTask struct {
	ID        string `json:"id,optional"`
	Payload   string `json:"payload,optional"`
	DelayTime int64  `json:"delay_time,optional"` // Unix时间戳，表示执行时间
}
