// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetCouponReq struct {
	CouponId   int64  `form:"couponId,optional"`   //优惠劵id
	CouponName string `form:"couponName,optional"` //优惠劵名称
}

type GetCouponResp struct {
	CouponId   int64  `json:"couponId"`   //优惠劵id
	CouponName string `json:"couponName"` //优惠劵名称
	DeAmount   int    `json:"deAmount"`   //抵扣金额
}

type InsertCouponReq struct {
	CouponId   int64  `json:"couponId"`   //优惠劵id
	CouponName string `json:"couponName"` //优惠劵名称
	DeAmount   int    `json:"deAmount"`   //抵扣金额
	Remark     string `json:"remark,optional"`     //备注
}
