// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: anonymous_user.proto

package server

import (
	"context"

	"user-service/internal/logic"
	"user-service/internal/svc"
	"user-service/proto/rpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUserByName(ctx context.Context, in *user.UserReq) (*user.UserResp, error) {
	l := logic.NewGetUserByNameLogic(ctx, s.svcCtx)
	return l.GetUserByName(in)
}
