worker_processes auto;
error_log /usr/local/openresty/nginx/logs/error.log info;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format logf '[$time_local] $remote_addr - $host $request_uri '
                        'status=$status bytes=$body_bytes_sent '
                        'rt=$request_time uct=$upstream_connect_time '
                        'uht=$upstream_header_time urt=$upstream_response_time '
                        'req_id=$request_id '
                        'domain=$http_host';

    access_log /usr/local/openresty/nginx/logs/access.log logf buffer=32k flush=5s;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;


    server {
        listen 80;
        server_name _;

        location /ok {
            access_log off;
            return 200 ":80 is OK\n";
            add_header Content-Type text/plain;
        }
    }
}
