// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"grpc_order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// http://127.0.0.1:9092/order/info?orderId=678
				// 获取订单信息
				Method:  http.MethodGet,
				Path:    "/order/info",
				Handler: orderInfoHandler(serverCtx),
			},
			{
				// 新增订单
				Method:  http.MethodPost,
				Path:    "/order/info",
				Handler: InsertOrderInfoHandler(serverCtx),
			},
		},
	)
}
