// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_zero_11_cron/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// http:127.0.0.1:8080/cron/task1
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/cron/task1",
				Handler: cronTask1Handler(serverCtx),
			},
		},
	)
}
