// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/tls.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsRequest) Reset() {
	*x = TlsRequest{}
	mi := &file_proto_tls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsRequest) ProtoMessage() {}

func (x *TlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsRequest.ProtoReflect.Descriptor instead.
func (*TlsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tls_proto_rawDescGZIP(), []int{0}
}

func (x *TlsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsResponse) Reset() {
	*x = TlsResponse{}
	mi := &file_proto_tls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsResponse) ProtoMessage() {}

func (x *TlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsResponse.ProtoReflect.Descriptor instead.
func (*TlsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tls_proto_rawDescGZIP(), []int{1}
}

func (x *TlsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_tls_proto protoreflect.FileDescriptor

const file_proto_tls_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tls.proto\x12\x05proto\" \n" +
	"\n" +
	"TlsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\vTlsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2C\n" +
	"\n" +
	"TlsService\x125\n" +
	"\fTlsInterface\x12\x11.proto.TlsRequest\x1a\x12.proto.TlsResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_tls_proto_rawDescOnce sync.Once
	file_proto_tls_proto_rawDescData []byte
)

func file_proto_tls_proto_rawDescGZIP() []byte {
	file_proto_tls_proto_rawDescOnce.Do(func() {
		file_proto_tls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tls_proto_rawDesc), len(file_proto_tls_proto_rawDesc)))
	})
	return file_proto_tls_proto_rawDescData
}

var file_proto_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tls_proto_goTypes = []any{
	(*TlsRequest)(nil),  // 0: proto.TlsRequest
	(*TlsResponse)(nil), // 1: proto.TlsResponse
}
var file_proto_tls_proto_depIdxs = []int32{
	0, // 0: proto.TlsService.TlsInterface:input_type -> proto.TlsRequest
	1, // 1: proto.TlsService.TlsInterface:output_type -> proto.TlsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tls_proto_init() }
func file_proto_tls_proto_init() {
	if File_proto_tls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tls_proto_rawDesc), len(file_proto_tls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tls_proto_goTypes,
		DependencyIndexes: file_proto_tls_proto_depIdxs,
		MessageInfos:      file_proto_tls_proto_msgTypes,
	}.Build()
	File_proto_tls_proto = out.File
	file_proto_tls_proto_goTypes = nil
	file_proto_tls_proto_depIdxs = nil
}
