// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/tls.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TlsService_TlsInterface_FullMethodName = "/proto.TlsService/TlsInterface"
)

// TlsServiceClient is the client API for TlsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TlsServiceClient interface {
	TlsInterface(ctx context.Context, in *TlsRequest, opts ...grpc.CallOption) (*TlsResponse, error)
}

type tlsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTlsServiceClient(cc grpc.ClientConnInterface) TlsServiceClient {
	return &tlsServiceClient{cc}
}

func (c *tlsServiceClient) TlsInterface(ctx context.Context, in *TlsRequest, opts ...grpc.CallOption) (*TlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TlsResponse)
	err := c.cc.Invoke(ctx, TlsService_TlsInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TlsServiceServer is the server API for TlsService service.
// All implementations must embed UnimplementedTlsServiceServer
// for forward compatibility.
type TlsServiceServer interface {
	TlsInterface(context.Context, *TlsRequest) (*TlsResponse, error)
	mustEmbedUnimplementedTlsServiceServer()
}

// UnimplementedTlsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTlsServiceServer struct{}

func (UnimplementedTlsServiceServer) TlsInterface(context.Context, *TlsRequest) (*TlsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TlsInterface not implemented")
}
func (UnimplementedTlsServiceServer) mustEmbedUnimplementedTlsServiceServer() {}
func (UnimplementedTlsServiceServer) testEmbeddedByValue()                    {}

// UnsafeTlsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TlsServiceServer will
// result in compilation errors.
type UnsafeTlsServiceServer interface {
	mustEmbedUnimplementedTlsServiceServer()
}

func RegisterTlsServiceServer(s grpc.ServiceRegistrar, srv TlsServiceServer) {
	// If the following call pancis, it indicates UnimplementedTlsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TlsService_ServiceDesc, srv)
}

func _TlsService_TlsInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TlsServiceServer).TlsInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TlsService_TlsInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TlsServiceServer).TlsInterface(ctx, req.(*TlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TlsService_ServiceDesc is the grpc.ServiceDesc for TlsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TlsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TlsService",
	HandlerType: (*TlsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TlsInterface",
			Handler:    _TlsService_TlsInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tls.proto",
}
