// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/interceptor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterceptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptorRequest) Reset() {
	*x = InterceptorRequest{}
	mi := &file_proto_interceptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorRequest) ProtoMessage() {}

func (x *InterceptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interceptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorRequest.ProtoReflect.Descriptor instead.
func (*InterceptorRequest) Descriptor() ([]byte, []int) {
	return file_proto_interceptor_proto_rawDescGZIP(), []int{0}
}

func (x *InterceptorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InterceptorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptorResponse) Reset() {
	*x = InterceptorResponse{}
	mi := &file_proto_interceptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorResponse) ProtoMessage() {}

func (x *InterceptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interceptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorResponse.ProtoReflect.Descriptor instead.
func (*InterceptorResponse) Descriptor() ([]byte, []int) {
	return file_proto_interceptor_proto_rawDescGZIP(), []int{1}
}

func (x *InterceptorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_interceptor_proto protoreflect.FileDescriptor

const file_proto_interceptor_proto_rawDesc = "" +
	"\n" +
	"\x17proto/interceptor.proto\x12\x05proto\"(\n" +
	"\x12InterceptorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13InterceptorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2c\n" +
	"\x12InterceptorService\x12M\n" +
	"\x14InterceptorInterface\x12\x19.proto.InterceptorRequest\x1a\x1a.proto.InterceptorResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_interceptor_proto_rawDescOnce sync.Once
	file_proto_interceptor_proto_rawDescData []byte
)

func file_proto_interceptor_proto_rawDescGZIP() []byte {
	file_proto_interceptor_proto_rawDescOnce.Do(func() {
		file_proto_interceptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interceptor_proto_rawDesc), len(file_proto_interceptor_proto_rawDesc)))
	})
	return file_proto_interceptor_proto_rawDescData
}

var file_proto_interceptor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_interceptor_proto_goTypes = []any{
	(*InterceptorRequest)(nil),  // 0: proto.InterceptorRequest
	(*InterceptorResponse)(nil), // 1: proto.InterceptorResponse
}
var file_proto_interceptor_proto_depIdxs = []int32{
	0, // 0: proto.InterceptorService.InterceptorInterface:input_type -> proto.InterceptorRequest
	1, // 1: proto.InterceptorService.InterceptorInterface:output_type -> proto.InterceptorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_interceptor_proto_init() }
func file_proto_interceptor_proto_init() {
	if File_proto_interceptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interceptor_proto_rawDesc), len(file_proto_interceptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interceptor_proto_goTypes,
		DependencyIndexes: file_proto_interceptor_proto_depIdxs,
		MessageInfos:      file_proto_interceptor_proto_msgTypes,
	}.Build()
	File_proto_interceptor_proto = out.File
	file_proto_interceptor_proto_goTypes = nil
	file_proto_interceptor_proto_depIdxs = nil
}
