// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"
	"time"

	"jwt_gen/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/anonymous_user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/anonymous_user/info",
				Handler: userInfoHandler(serverCtx),
			},
		},
		// jwt认证， go-zero 框架自动认证 请求头里面的Authorization字段，
		// 读取 token 信息的时候，使用 uuid := this.ctx.Value("uuid") 即可
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	// 以下是自定义读取权限认证的演示
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				serverCtx.JwtAuthMiddleware.JwtAuthorization,
				serverCtx.UserAgentMiddleware.Handle,
			},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/anonymous_user/getUserById",
					Handler: getUserByIdHandler(serverCtx),
				},
			}..., // 使用 ... 将数组展开
		),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
