// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0--rc2
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcOrderService_GrpcGetOrder_FullMethodName = "/GrpcOrderService/GrpcGetOrder"
)

// GrpcOrderServiceClient is the client API for GrpcOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcOrderServiceClient interface {
	GrpcGetOrder(ctx context.Context, in *GrpcGetOrderReq, opts ...grpc.CallOption) (*GrpcGetOrderResp, error)
}

type grpcOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcOrderServiceClient(cc grpc.ClientConnInterface) GrpcOrderServiceClient {
	return &grpcOrderServiceClient{cc}
}

func (c *grpcOrderServiceClient) GrpcGetOrder(ctx context.Context, in *GrpcGetOrderReq, opts ...grpc.CallOption) (*GrpcGetOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrpcGetOrderResp)
	err := c.cc.Invoke(ctx, GrpcOrderService_GrpcGetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcOrderServiceServer is the server API for GrpcOrderService service.
// All implementations must embed UnimplementedGrpcOrderServiceServer
// for forward compatibility.
type GrpcOrderServiceServer interface {
	GrpcGetOrder(context.Context, *GrpcGetOrderReq) (*GrpcGetOrderResp, error)
	mustEmbedUnimplementedGrpcOrderServiceServer()
}

// UnimplementedGrpcOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcOrderServiceServer struct{}

func (UnimplementedGrpcOrderServiceServer) GrpcGetOrder(context.Context, *GrpcGetOrderReq) (*GrpcGetOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcGetOrder not implemented")
}
func (UnimplementedGrpcOrderServiceServer) mustEmbedUnimplementedGrpcOrderServiceServer() {}
func (UnimplementedGrpcOrderServiceServer) testEmbeddedByValue()                          {}

// UnsafeGrpcOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcOrderServiceServer will
// result in compilation errors.
type UnsafeGrpcOrderServiceServer interface {
	mustEmbedUnimplementedGrpcOrderServiceServer()
}

func RegisterGrpcOrderServiceServer(s grpc.ServiceRegistrar, srv GrpcOrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrpcOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcOrderService_ServiceDesc, srv)
}

func _GrpcOrderService_GrpcGetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcGetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcOrderServiceServer).GrpcGetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcOrderService_GrpcGetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcOrderServiceServer).GrpcGetOrder(ctx, req.(*GrpcGetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcOrderService_ServiceDesc is the grpc.ServiceDesc for GrpcOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcOrderService",
	HandlerType: (*GrpcOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcGetOrder",
			Handler:    _GrpcOrderService_GrpcGetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
