// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: order.proto

package server

import (
	"context"

	"grpc_order/grpc/order"
	"grpc_order/internal/logic"
	"grpc_order/internal/svc"
)

type GrpcOrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedGrpcOrderServiceServer
}

func NewGrpcOrderServiceServer(svcCtx *svc.ServiceContext) *GrpcOrderServiceServer {
	return &GrpcOrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GrpcOrderServiceServer) GrpcGetOrder(ctx context.Context, in *order.GrpcGetOrderReq) (*order.GrpcGetOrderResp, error) {
	l := logic.NewGrpcGetOrderLogic(ctx, s.svcCtx)
	return l.GrpcGetOrder(in)
}
