// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	hello "go-dev/src/test8_framework/framework_02_micro/micro_05_go_zero/go_zero_04_dsl_api/api_03_router_prefix/api_gen/internal/handler/hello"
	"go-dev/src/test8_framework/framework_02_micro/micro_05_go_zero/go_zero_04_dsl_api/api_03_router_prefix/api_gen/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sayHello/:name",
				Handler: hello.Hello1Handler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/hello"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sayHello/:name",
				Handler: hello.Hello2Handler(serverCtx),
			},
		},
		rest.WithPrefix("/v2"),
	)
}
