---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/8 17:40
--- serialize.lua
--- 纯 Lua 手写 JSON 序列化（JSON encoder）

local _M = {}
_M.__index = _M

local function escape_str(s)
    s = s:gsub("\\", "\\\\")
         :gsub("\"", "\\\"")
         :gsub("\n", "\\n")
         :gsub("\r", "\\r")
         :gsub("\t", "\\t")
    return s
end

local function encode_value(v)
    local t = type(v)
    if t == "string"  then return "\"" .. escape_str(v) .. "\""
    elseif t == "number" or t == "boolean" then return tostring(v)
    elseif t == "table" then return _M:encode(v)
    elseif t == "nil" then return "null"
    else error("unsupported type: " .. t)
    end
end


-- 模块对外接口：encode(table)
function _M:encode(tbl)
    -- 数组（纯数字索引）
    local is_array = true
    local max = 0
    for k,_ in pairs(tbl) do
        if type(k) ~= "number" then
            is_array = false
            break
        end
        if k > max then max = k end
    end

    if is_array then
        local out = {}
        for i=1,max do
            out[#out+1] = encode_value(tbl[i])
        end
        return "[" .. table.concat(out, ",") .. "]"
    end

    -- 对象（按 _order 保证顺序）
    local out = {}

    local order = rawget(tbl, "_order")
    if order then
        -- 按顺序输出
        for _, key in ipairs(order) do
            local v = tbl[key]
            out[#out+1] = "\"" .. key .. "\":" .. encode_value(v)
        end
    else
        -- fallback（没有顺序时按字母排序）
        local keys = {}
        for k,_ in pairs(tbl) do
            if k ~= "_order" then keys[#keys+1] = k end
        end
        table.sort(keys)
        for _, key in ipairs(keys) do
            out[#out+1] = "\"" .. key .. "\":" .. encode_value(tbl[key])
        end
    end

    return "{" .. table.concat(out, ",") .. "}"
end

return _M
