---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/8 16:48
--- test20.lua
--- lua操作文件
---
--[[
Lua I/O 库用于读取和处理文件。分为简单模式（和C一样）、完全模式。
简单模式（simple model）拥有一个当前输入文件和一个当前输出文件，并且提供针对这些文件相关的操作。
完全模式（complete model） 使用外部的文件句柄来实现。它以一种面对对象的形式，将所有的文件操作定义为文件句柄的方法
]]

-- 以下演示简单模式
--file = io.open (filename [, mode])
--[[
可选的打开文件的模式如下表所示。
模式	描述
"r"	只读模式，这也是对已存在的文件的默认打开模式。
"w"	可写模式，允许修改已经存在的文件和创建新文件。
"a"	追加模式，对于已存的文件允许追加新内容，但不允许修改原有内容，同时也可以创建新文件。
"r+"	读写模式打开已存的在文件。
"w+"	如果文件已存在则删除文件中数据；若文件不存在则新建文件。读写模式打开。
"a+"	以可读的追加模式打开已存在文件，若文件不存在则新建文件。
]]


-- 简单的读取文件
function test201()
    -- 使用io工具方法，不适应file对象方法

    -- 以只读方式打开文件
    file = io.open("test01.lua", "r")

    ---- 设置默认输出文件为 test.lua
    io.input(file)

    -- 输出文件第一行
    print("读取文件1 "..io.read())
    print("读取文件2 "..io.read())

    -- 关闭打开的文件
    io.close(file)
end
--test201()

-- 完全模式 读取文件
function test202()
    local file = io.open("test03.lua", "r")

    print("读取1: ", file:read())
    print("读取2: ", file:read())
    print("读取3: ", file:read())

    -- 使用lines迭代器遍历
    for line in file:lines() do
        print("line: ", line)
    end

    file:close()

end
--test202()

--local logFile = io.open("app22.log", "r")
--if not logFile then
--    print("找不到该文件")
--    return
--end
--print("有文件")


local json = require "serialize"

-- 完全模式 写文件
function test203()
    local logFile = io.open("app.log", "a+")
    if not logFile then
        print("文件指针不存在")
        return
    end

    local log_item = {
        name = "LXC",
        age = 18,
        active = true,
        tags = { "lua", "openresty", "cdn" },
        config = { retry = 3 }
    }

    local log_str = json:encode(log_item)

    logFile:write(log_str .. "\n")

    logFile:flush()
    logFile:close()
    print("日志写入成功")
end
test203()



---- 以附加的方式打开只写文件
--file = io.open("test.lua", "a")
--
---- 设置默认输出文件为 test.lua
--io.output(file)
----
---- 在文件最后一行添加 Lua 注释
--io.write("--  test.lua 文件末尾注释")
--
---- 关闭打开的文件
--io.close(file)


--local file = io.open ("app.log", "a+")
--file.write("只读模式，这也是对已存在的文件的默认打开模式")
--file.write("可写模式，允许修改已经存在的文件和创建新文件。")
--file.write("追加模式，对于已存的文件允许追加新内容，但不允许修改原有内容，同时也可以创建新文件。")





