// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: user.proto

package user

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (

	UserService interface {
		GetUserByName(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUserByName(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error) {
	client := NewUserServiceClient(m.cli.Conn())
	return client.GetUserByName(ctx, in, opts...)
}
