// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type RabbitmqApiReq struct {
	Queue    string `form:"queue,optional"`
	Router   string `form:"router,optional"`
	Exchange string `form:"exchange,optional"`
	Msg      string `form:"msg,optional"`
}
