// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: coupon.proto

package grpccouponservice

import (
	"context"

	"grpc_coupon/grpc/coupon"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GrpcGetCouponReq  = coupon.GrpcGetCouponReq
	GrpcGetCouponResp = coupon.GrpcGetCouponResp

	GrpcCouponService interface {
		GrpcGetCoupon(ctx context.Context, in *GrpcGetCouponReq, opts ...grpc.CallOption) (*GrpcGetCouponResp, error)
	}

	defaultGrpcCouponService struct {
		cli zrpc.Client
	}
)

func NewGrpcCouponService(cli zrpc.Client) GrpcCouponService {
	return &defaultGrpcCouponService{
		cli: cli,
	}
}

func (m *defaultGrpcCouponService) GrpcGetCoupon(ctx context.Context, in *GrpcGetCouponReq, opts ...grpc.CallOption) (*GrpcGetCouponResp, error) {
	client := coupon.NewGrpcCouponServiceClient(m.cli.Conn())
	return client.GrpcGetCoupon(ctx, in, opts...)
}
