// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types


type CronTaskReq struct {
	TaskId   int64  `form:"taskId,optional"`   //用户id
	TaskName string `form:"taskName,optional"` //用户名
}

type CronTaskResp struct {
	TaskId   int64  `json:"taskId"`   //用户id
	TaskName string `json:"taskName"` //用户名
	Address  string `json:"address"`  //地址
	Age      int    `json:"age"`      //年龄
}
