---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/5 10:03
--- FilePath: lua/lib/table_ext.lua
---

-- 本文件对lua的table方法进行扩展


-- [[ 扩展 table.contains ]]--
function table.contains(tbl, element)
    if tbl == nil then
        return false
    end

    for _, value in pairs(tbl) do
        if value == element then
            return true
        end
    end
    return false
end

-- [[ 扩展 table长度 ]]--
function table.count(table)
    local count = 0

    for k, v in pairs(table) do
        count = count + 1
    end

    return count
end


-- [[ 合并table ]]--
-- 合并数组
function table.addRange(sourceTable, addTable)
    for k, v in pairs(addTable) do
        table.insert(sourceTable, v)
    end
end


-- [[ 复制table ]]--
function table.copy(st)
    local tab = {}
    for k, v in pairs(st or {}) do
        if type(v) ~= "table" then
            tab[k] = v
        else
            tab[k] = table.copy(v)
        end
    end
    return tab
end

-- [[ 复制table 到 源table ]]--
function table.copyTo(source, des)
    local tab = des
    for k, v in pairs(source or {}) do
        if type(v) ~= "table" then
            tab[k] = v
        else
            tab[k] = table.copy(v)
        end
    end
end

-- [[ 获取index ]]--
function table.indexOf(list, target, from, useMaxN)
    local len = (useMaxN and #list) or table.maxn(list)
    if from == nil then
        from = 1
    end
    for i = from, len do
        if list[i] == target then
            return i
        end
    end
    return -1
end

-- [[ 反转table ]]--
function table.reverse(t)
    local l = #t
    local c = math.floor(l / 2)
    for i = 1, c do
        local v = t[i]
        t[i] = t[l - i + 1]
        t[l - i + 1] = v
    end
end

-- [[ table map ]]--
function table.map(t, fun)
    local l = {}
    for k, v in pairs(t) do
        l[k] = fun(v, k)
    end
    return l
end

-- [[ 过滤table ]]--
function table.select(t, fun)
    local l = {}
    for k, v in pairs(t) do
        if fun(v, k) then
            l[k] = v
        end
    end
    return l
end

------------------------------
-- 查找元素索引（仅数组部分）
------------------------------
function table.index_of(tbl, element)
    if tbl == nil then return nil end
    for i, v in ipairs(tbl) do
        if v == element then
            return i
        end
    end
    return nil
end

------------------------------
-- 合并两个 table
-- 同名 key 会被覆盖
------------------------------
function table.merge(t1, t2)
    if t1 == nil or t2 == nil then return t1 end
    for k, v in pairs(t2) do
        t1[k] = v
    end
    return t1
end

------------------------------
-- 数组去重
------------------------------
function table.unique(tbl)
    if tbl == nil then return nil end
    local exist = {}
    local new_tbl = {}

    for _, v in ipairs(tbl) do
        if not exist[v] then
            exist[v] = true
            table.insert(new_tbl, v)
        end
    end
    return new_tbl
end

------------------------------
-- 深拷贝
------------------------------
function table.deep_copy(orig)
    if type(orig) ~= "table" then return orig end
    local copy = {}
    for k, v in pairs(orig) do
        copy[k] = table.deep_copy(v)
    end
    return copy
end

------------------------------
-- 浅拷贝
------------------------------
function table.shallow_copy(orig)
    if type(orig) ~= "table" then return orig end
    local copy = {}
    for k, v in pairs(orig) do
        copy[k] = v
    end
    return copy
end

------------------------------
-- 获取所有 keys
------------------------------
function table.keys(tbl)
    local ks = {}
    for k, _ in pairs(tbl) do
        table.insert(ks, k)
    end
    return ks
end

------------------------------
-- 获取所有 values
------------------------------
function table.values(tbl)
    local vs = {}
    for _, v in pairs(tbl) do
        table.insert(vs, v)
    end
    return vs
end

------------------------------
-- Debug: 打印 table
------------------------------
function table.print(tbl, indent)
    indent = indent or 0
    local prefix = string.rep(" ", indent)

    if type(tbl) ~= "table" then
        print(prefix .. tostring(tbl))
        return
    end

    print(prefix .. "{")
    for k, v in pairs(tbl) do
        io.write(prefix .. "  [" .. tostring(k) .. "] = ")
        if type(v) == "table" then
            table.print(v, indent + 4)
        else
            print(tostring(v))
        end
    end
    print(prefix .. "}")
end

-- 过滤: 返回一个包含满足条件的新数组
function table.filter(tbl, fn)
    local result = {}
    for k, v in pairs(tbl) do
        if fn(v, k, tbl) then
            result[#result + 1] = v
        end
    end
    return result
end

-- 映射: 对每个元素执行 fn，返回新的数组
function table.map(tbl, func)
    local result = {}
    for k, v in pairs(tbl) do
        result[#result + 1] = func(v, k, tbl)
    end
    return result
end

-- 累积: 对数组进行累积计算
function table.reduce(tbl, func, initial)
    local acc = initial
    local started = initial ~= nil

    for k, v in pairs(tbl) do
        if not started then
            acc = v
            started = true
        else
            acc = func(acc, v, k, tbl)
        end
    end

    return acc
end


-- 浅拷贝
function table.clone(tbl)
    local result = {}
    for k, v in pairs(tbl) do
        result[k] = v
    end
    return result
end

-- 深拷贝
function table.deepcopy(tbl, seen)
    if type(tbl) ~= "table" then return tbl end
    if seen and seen[tbl] then return seen[tbl] end

    local result = {}
    seen = seen or {}
    seen[tbl] = result

    for k, v in pairs(tbl) do
        result[table.deepcopy(k, seen)] = table.deepcopy(v, seen)
    end

    return result
end

-- 反转数组（仅对数组部分）
function table.reverse(tbl)
    local result = {}
    local n = #tbl
    for i = n, 1, -1 do
        result[n - i + 1] = tbl[i]
    end
    return result
end

-- slice（仿 JS array.slice）
function table.slice(tbl, start_idx, end_idx)
    local result = {}
    local len = #tbl

    start_idx = start_idx or 1
    end_idx = end_idx or len

    if start_idx < 0 then start_idx = len + start_idx + 1 end
    if end_idx < 0 then end_idx = len + end_idx + 1 end

    for i = start_idx, end_idx do
        if tbl[i] ~= nil then
            result[#result + 1] = tbl[i]
        end
    end

    return result
end

-- find: 查找元素位置
function table.find(tbl, value)
    for i, v in pairs(tbl) do
        if v == value then return i end
    end
    return nil
end

-- group_by
function table.group_by(tbl, fn)
    local result = {}
    for k, v in pairs(tbl) do
        local key = fn(v, k, tbl)
        result[key] = result[key] or {}
        table.insert(result[key], v)
    end
    return result
end

-- count_by
function table.count_by(tbl, fn)
    local result = {}
    for k, v in pairs(tbl) do
        local key = fn(v, k, tbl)
        result[key] = (result[key] or 0) + 1
    end
    return result
end

-- sort_by（仿 lodash）
function table.sort_by(tbl, fn)
    local arr = table.clone(tbl)
    table.sort(arr, function(a, b)
        return fn(a) < fn(b)
    end)
    return arr
end

-- flatten（扁平化 1 层）
function table.flatten(tbl)
    local result = {}
    for _, v in ipairs(tbl) do
        if type(v) == "table" then
            for _, vv in ipairs(v) do
                result[#result + 1] = vv
            end
        else
            result[#result + 1] = v
        end
    end
    return result
end

-- every（数组所有元素满足条件）
function table.every(tbl, fn)
    for k, v in pairs(tbl) do
        if not fn(v, k, tbl) then
            return false
        end
    end
    return true
end

-- some（数组至少一个满足条件）
function table.some(tbl, fn)
    for k, v in pairs(tbl) do
        if fn(v, k, tbl) then
            return true
        end
    end
    return false
end


--[[
将扩展的table方法返回

然后在 项目入口文件（如 init.lua, main.lua, OpenResty 的 init_by_lua_block）统一加载：
require "lua.table_ext"

只需要require就可以了，不需要将其赋给local变量，因为这些方法已经挂在table上了，而table由系统去加载到每一个lua文件

或者去改变 lua_package_path 变量

lua_package_path "/path/to/your/project/lua/?.lua;;";

]]--
return table


