// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/base2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义枚举消息
type Color int32

const (
	// 定义枚举消息时，编号0作为枚举的默认值，一般使用无意义的值代替，且必须保证至少有一个编号为 0 的枚举项。
	Color_UNKNOWN Color = 0
	Color_RED     Color = 11
	Color_GREEN   Color = 2
	Color_BLUE    Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0:  "UNKNOWN",
		11: "RED",
		2:  "GREEN",
		3:  "BLUE",
	}
	Color_value = map[string]int32{
		"UNKNOWN": 0,
		"RED":     11,
		"GREEN":   2,
		"BLUE":    3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_base2_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_proto_base2_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_proto_base2_proto_rawDescGZIP(), []int{0}
}

var File_proto_base2_proto protoreflect.FileDescriptor

const file_proto_base2_proto_rawDesc = "" +
	"\n" +
	"\x11proto/base2.proto*2\n" +
	"\x05Color\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03RED\x10\v\x12\t\n" +
	"\x05GREEN\x10\x02\x12\b\n" +
	"\x04BLUE\x10\x03B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_base2_proto_rawDescOnce sync.Once
	file_proto_base2_proto_rawDescData []byte
)

func file_proto_base2_proto_rawDescGZIP() []byte {
	file_proto_base2_proto_rawDescOnce.Do(func() {
		file_proto_base2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_base2_proto_rawDesc), len(file_proto_base2_proto_rawDesc)))
	})
	return file_proto_base2_proto_rawDescData
}

var file_proto_base2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_base2_proto_goTypes = []any{
	(Color)(0), // 0: Color
}
var file_proto_base2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_base2_proto_init() }
func file_proto_base2_proto_init() {
	if File_proto_base2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_base2_proto_rawDesc), len(file_proto_base2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_base2_proto_goTypes,
		DependencyIndexes: file_proto_base2_proto_depIdxs,
		EnumInfos:         file_proto_base2_proto_enumTypes,
	}.Build()
	File_proto_base2_proto = out.File
	file_proto_base2_proto_goTypes = nil
	file_proto_base2_proto_depIdxs = nil
}
