// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/base.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Msg   string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 使用 repeated 来表示这个字段是一个数组
	InnerList []*GetBaseRequestInner `protobuf:"bytes,3,rep,name=innerList,proto3" json:"innerList,omitempty"`
	// 使用 map<string, GetBaseRequestMap> 来定义key-val的数据结构
	MapData       map[string]*GetBaseRequestMap `protobuf:"bytes,5,rep,name=mapData,proto3" json:"mapData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseRequest) Reset() {
	*x = GetBaseRequest{}
	mi := &file_proto_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseRequest) ProtoMessage() {}

func (x *GetBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseRequest.ProtoReflect.Descriptor instead.
func (*GetBaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_base_proto_rawDescGZIP(), []int{0}
}

func (x *GetBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBaseRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetBaseRequest) GetInnerList() []*GetBaseRequestInner {
	if x != nil {
		return x.InnerList
	}
	return nil
}

func (x *GetBaseRequest) GetMapData() map[string]*GetBaseRequestMap {
	if x != nil {
		return x.MapData
	}
	return nil
}

type GetBaseRequestInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           string                 `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar           string                 `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseRequestInner) Reset() {
	*x = GetBaseRequestInner{}
	mi := &file_proto_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseRequestInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseRequestInner) ProtoMessage() {}

func (x *GetBaseRequestInner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseRequestInner.ProtoReflect.Descriptor instead.
func (*GetBaseRequestInner) Descriptor() ([]byte, []int) {
	return file_proto_base_proto_rawDescGZIP(), []int{1}
}

func (x *GetBaseRequestInner) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

func (x *GetBaseRequestInner) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

type GetBaseRequestMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo1          string                 `protobuf:"bytes,1,opt,name=foo1,proto3" json:"foo1,omitempty"`
	Bar2          string                 `protobuf:"bytes,2,opt,name=bar2,proto3" json:"bar2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseRequestMap) Reset() {
	*x = GetBaseRequestMap{}
	mi := &file_proto_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseRequestMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseRequestMap) ProtoMessage() {}

func (x *GetBaseRequestMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseRequestMap.ProtoReflect.Descriptor instead.
func (*GetBaseRequestMap) Descriptor() ([]byte, []int) {
	return file_proto_base_proto_rawDescGZIP(), []int{2}
}

func (x *GetBaseRequestMap) GetFoo1() string {
	if x != nil {
		return x.Foo1
	}
	return ""
}

func (x *GetBaseRequestMap) GetBar2() string {
	if x != nil {
		return x.Bar2
	}
	return ""
}

type GetBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           string                 `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Data3         string                 `protobuf:"bytes,12,opt,name=data3,proto3" json:"data3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseResponse) Reset() {
	*x = GetBaseResponse{}
	mi := &file_proto_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseResponse) ProtoMessage() {}

func (x *GetBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseResponse.ProtoReflect.Descriptor instead.
func (*GetBaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_base_proto_rawDescGZIP(), []int{3}
}

func (x *GetBaseResponse) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

func (x *GetBaseResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetBaseResponse) GetData3() string {
	if x != nil {
		return x.Data3
	}
	return ""
}

var File_proto_base_proto protoreflect.FileDescriptor

const file_proto_base_proto_rawDesc = "" +
	"\n" +
	"\x10proto/base.proto\"\xf2\x01\n" +
	"\x0eGetBaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x122\n" +
	"\tinnerList\x18\x03 \x03(\v2\x14.GetBaseRequestInnerR\tinnerList\x126\n" +
	"\amapData\x18\x05 \x03(\v2\x1c.GetBaseRequest.MapDataEntryR\amapData\x1aN\n" +
	"\fMapDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.GetBaseRequestMapR\x05value:\x028\x01\"9\n" +
	"\x13GetBaseRequestInner\x12\x10\n" +
	"\x03foo\x18\x01 \x01(\tR\x03foo\x12\x10\n" +
	"\x03bar\x18\x02 \x01(\tR\x03bar\";\n" +
	"\x11GetBaseRequestMap\x12\x12\n" +
	"\x04foo1\x18\x01 \x01(\tR\x04foo1\x12\x12\n" +
	"\x04bar2\x18\x02 \x01(\tR\x04bar2\"M\n" +
	"\x0fGetBaseResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\tR\x03res\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x14\n" +
	"\x05data3\x18\f \x01(\tR\x05data32;\n" +
	"\vBaseService\x12,\n" +
	"\aGetBase\x12\x0f.GetBaseRequest\x1a\x10.GetBaseResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_base_proto_rawDescOnce sync.Once
	file_proto_base_proto_rawDescData []byte
)

func file_proto_base_proto_rawDescGZIP() []byte {
	file_proto_base_proto_rawDescOnce.Do(func() {
		file_proto_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_base_proto_rawDesc), len(file_proto_base_proto_rawDesc)))
	})
	return file_proto_base_proto_rawDescData
}

var file_proto_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_base_proto_goTypes = []any{
	(*GetBaseRequest)(nil),      // 0: GetBaseRequest
	(*GetBaseRequestInner)(nil), // 1: GetBaseRequestInner
	(*GetBaseRequestMap)(nil),   // 2: GetBaseRequestMap
	(*GetBaseResponse)(nil),     // 3: GetBaseResponse
	nil,                         // 4: GetBaseRequest.MapDataEntry
}
var file_proto_base_proto_depIdxs = []int32{
	1, // 0: GetBaseRequest.innerList:type_name -> GetBaseRequestInner
	4, // 1: GetBaseRequest.mapData:type_name -> GetBaseRequest.MapDataEntry
	2, // 2: GetBaseRequest.MapDataEntry.value:type_name -> GetBaseRequestMap
	0, // 3: BaseService.GetBase:input_type -> GetBaseRequest
	3, // 4: BaseService.GetBase:output_type -> GetBaseResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_base_proto_init() }
func file_proto_base_proto_init() {
	if File_proto_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_base_proto_rawDesc), len(file_proto_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_base_proto_goTypes,
		DependencyIndexes: file_proto_base_proto_depIdxs,
		MessageInfos:      file_proto_base_proto_msgTypes,
	}.Build()
	File_proto_base_proto = out.File
	file_proto_base_proto_goTypes = nil
	file_proto_base_proto_depIdxs = nil
}
