// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/base5.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 嵌套的消息定义
type Outer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// 定义任意数据类型
	Details       []*anypb.Any `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_proto_base5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_proto_base5_proto_rawDescGZIP(), []int{0}
}

func (x *Outer) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Outer) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type Outer_Inner1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	You           int32                  `protobuf:"varint,1,opt,name=you,proto3" json:"you,omitempty"`
	Are           int32                  `protobuf:"varint,2,opt,name=are,proto3" json:"are,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer_Inner1) Reset() {
	*x = Outer_Inner1{}
	mi := &file_proto_base5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer_Inner1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner1) ProtoMessage() {}

func (x *Outer_Inner1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner1.ProtoReflect.Descriptor instead.
func (*Outer_Inner1) Descriptor() ([]byte, []int) {
	return file_proto_base5_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Outer_Inner1) GetYou() int32 {
	if x != nil {
		return x.You
	}
	return 0
}

func (x *Outer_Inner1) GetAre() int32 {
	if x != nil {
		return x.Are
	}
	return 0
}

type Outer_Inner2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hhh   int32                  `protobuf:"varint,1,opt,name=hhh,proto3" json:"hhh,omitempty"`
	// Deprecated: Marked as deprecated in proto/base5.proto.
	Aaa           int32 `protobuf:"varint,2,opt,name=aaa,proto3" json:"aaa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer_Inner2) Reset() {
	*x = Outer_Inner2{}
	mi := &file_proto_base5_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer_Inner2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner2) ProtoMessage() {}

func (x *Outer_Inner2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base5_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner2.ProtoReflect.Descriptor instead.
func (*Outer_Inner2) Descriptor() ([]byte, []int) {
	return file_proto_base5_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Outer_Inner2) GetHhh() int32 {
	if x != nil {
		return x.Hhh
	}
	return 0
}

// Deprecated: Marked as deprecated in proto/base5.proto.
func (x *Outer_Inner2) GetAaa() int32 {
	if x != nil {
		return x.Aaa
	}
	return 0
}

type Outer_Inner1_Inner12 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hello         string                 `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	World         string                 `protobuf:"bytes,2,opt,name=world,proto3" json:"world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer_Inner1_Inner12) Reset() {
	*x = Outer_Inner1_Inner12{}
	mi := &file_proto_base5_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer_Inner1_Inner12) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner1_Inner12) ProtoMessage() {}

func (x *Outer_Inner1_Inner12) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base5_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner1_Inner12.ProtoReflect.Descriptor instead.
func (*Outer_Inner1_Inner12) Descriptor() ([]byte, []int) {
	return file_proto_base5_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Outer_Inner1_Inner12) GetHello() string {
	if x != nil {
		return x.Hello
	}
	return ""
}

func (x *Outer_Inner1_Inner12) GetWorld() string {
	if x != nil {
		return x.World
	}
	return ""
}

var File_proto_base5_proto protoreflect.FileDescriptor

const file_proto_base5_proto_rawDesc = "" +
	"\n" +
	"\x11proto/base5.proto\x1a\x19google/protobuf/any.proto\"\xde\x01\n" +
	"\x05Outer\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12.\n" +
	"\adetails\x18\b \x03(\v2\x14.google.protobuf.AnyR\adetails\x1ac\n" +
	"\x06Inner1\x12\x10\n" +
	"\x03you\x18\x01 \x01(\x05R\x03you\x12\x10\n" +
	"\x03are\x18\x02 \x01(\x05R\x03are\x1a5\n" +
	"\aInner12\x12\x14\n" +
	"\x05hello\x18\x01 \x01(\tR\x05hello\x12\x14\n" +
	"\x05world\x18\x02 \x01(\tR\x05world\x1a0\n" +
	"\x06Inner2\x12\x10\n" +
	"\x03hhh\x18\x01 \x01(\x05R\x03hhh\x12\x14\n" +
	"\x03aaa\x18\x02 \x01(\x05B\x02\x18\x01R\x03aaaB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_base5_proto_rawDescOnce sync.Once
	file_proto_base5_proto_rawDescData []byte
)

func file_proto_base5_proto_rawDescGZIP() []byte {
	file_proto_base5_proto_rawDescOnce.Do(func() {
		file_proto_base5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_base5_proto_rawDesc), len(file_proto_base5_proto_rawDesc)))
	})
	return file_proto_base5_proto_rawDescData
}

var file_proto_base5_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_base5_proto_goTypes = []any{
	(*Outer)(nil),                // 0: Outer
	(*Outer_Inner1)(nil),         // 1: Outer.Inner1
	(*Outer_Inner2)(nil),         // 2: Outer.Inner2
	(*Outer_Inner1_Inner12)(nil), // 3: Outer.Inner1.Inner12
	(*anypb.Any)(nil),            // 4: google.protobuf.Any
}
var file_proto_base5_proto_depIdxs = []int32{
	4, // 0: Outer.details:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_base5_proto_init() }
func file_proto_base5_proto_init() {
	if File_proto_base5_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_base5_proto_rawDesc), len(file_proto_base5_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_base5_proto_goTypes,
		DependencyIndexes: file_proto_base5_proto_depIdxs,
		MessageInfos:      file_proto_base5_proto_msgTypes,
	}.Build()
	File_proto_base5_proto = out.File
	file_proto_base5_proto_goTypes = nil
	file_proto_base5_proto_depIdxs = nil
}
