// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"grpc_user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: userInfoHandler(serverCtx),
			},
			{
				// 新增用户
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: InsertUserInfoHandler(serverCtx),
			},
		},
	)
}
