// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: coupon.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcGetCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      string                 `protobuf:"bytes,1,opt,name=couponId,proto3" json:"couponId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcGetCouponReq) Reset() {
	*x = GrpcGetCouponReq{}
	mi := &file_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcGetCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGetCouponReq) ProtoMessage() {}

func (x *GrpcGetCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGetCouponReq.ProtoReflect.Descriptor instead.
func (*GrpcGetCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcGetCouponReq) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

type GrpcGetCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      string                 `protobuf:"bytes,1,opt,name=couponId,proto3" json:"couponId,omitempty"`
	CouponName    string                 `protobuf:"bytes,2,opt,name=couponName,proto3" json:"couponName,omitempty"`
	DeAmount      int32                  `protobuf:"varint,3,opt,name=deAmount,proto3" json:"deAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcGetCouponResp) Reset() {
	*x = GrpcGetCouponResp{}
	mi := &file_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcGetCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGetCouponResp) ProtoMessage() {}

func (x *GrpcGetCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGetCouponResp.ProtoReflect.Descriptor instead.
func (*GrpcGetCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcGetCouponResp) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *GrpcGetCouponResp) GetCouponName() string {
	if x != nil {
		return x.CouponName
	}
	return ""
}

func (x *GrpcGetCouponResp) GetDeAmount() int32 {
	if x != nil {
		return x.DeAmount
	}
	return 0
}

var File_coupon_proto protoreflect.FileDescriptor

const file_coupon_proto_rawDesc = "" +
	"\n" +
	"\fcoupon.proto\".\n" +
	"\x10GrpcGetCouponReq\x12\x1a\n" +
	"\bcouponId\x18\x01 \x01(\tR\bcouponId\"k\n" +
	"\x11GrpcGetCouponResp\x12\x1a\n" +
	"\bcouponId\x18\x01 \x01(\tR\bcouponId\x12\x1e\n" +
	"\n" +
	"couponName\x18\x02 \x01(\tR\n" +
	"couponName\x12\x1a\n" +
	"\bdeAmount\x18\x03 \x01(\x05R\bdeAmount2K\n" +
	"\x11GrpcCouponService\x126\n" +
	"\rGrpcGetCoupon\x12\x11.GrpcGetCouponReq\x1a\x12.GrpcGetCouponRespB\x0fZ\r./grpc/couponb\x06proto3"

var (
	file_coupon_proto_rawDescOnce sync.Once
	file_coupon_proto_rawDescData []byte
)

func file_coupon_proto_rawDescGZIP() []byte {
	file_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)))
	})
	return file_coupon_proto_rawDescData
}

var file_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coupon_proto_goTypes = []any{
	(*GrpcGetCouponReq)(nil),  // 0: GrpcGetCouponReq
	(*GrpcGetCouponResp)(nil), // 1: GrpcGetCouponResp
}
var file_coupon_proto_depIdxs = []int32{
	0, // 0: GrpcCouponService.GrpcGetCoupon:input_type -> GrpcGetCouponReq
	1, // 1: GrpcCouponService.GrpcGetCoupon:output_type -> GrpcGetCouponResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coupon_proto_init() }
func file_coupon_proto_init() {
	if File_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_proto_msgTypes,
	}.Build()
	File_coupon_proto = out.File
	file_coupon_proto_goTypes = nil
	file_coupon_proto_depIdxs = nil
}
