// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0--rc2
// source: coupon.proto

package coupon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrpcCouponService_GrpcGetCoupon_FullMethodName = "/GrpcCouponService/GrpcGetCoupon"
)

// GrpcCouponServiceClient is the client API for GrpcCouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcCouponServiceClient interface {
	GrpcGetCoupon(ctx context.Context, in *GrpcGetCouponReq, opts ...grpc.CallOption) (*GrpcGetCouponResp, error)
}

type grpcCouponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcCouponServiceClient(cc grpc.ClientConnInterface) GrpcCouponServiceClient {
	return &grpcCouponServiceClient{cc}
}

func (c *grpcCouponServiceClient) GrpcGetCoupon(ctx context.Context, in *GrpcGetCouponReq, opts ...grpc.CallOption) (*GrpcGetCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrpcGetCouponResp)
	err := c.cc.Invoke(ctx, GrpcCouponService_GrpcGetCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcCouponServiceServer is the server API for GrpcCouponService service.
// All implementations must embed UnimplementedGrpcCouponServiceServer
// for forward compatibility.
type GrpcCouponServiceServer interface {
	GrpcGetCoupon(context.Context, *GrpcGetCouponReq) (*GrpcGetCouponResp, error)
	mustEmbedUnimplementedGrpcCouponServiceServer()
}

// UnimplementedGrpcCouponServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcCouponServiceServer struct{}

func (UnimplementedGrpcCouponServiceServer) GrpcGetCoupon(context.Context, *GrpcGetCouponReq) (*GrpcGetCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrpcGetCoupon not implemented")
}
func (UnimplementedGrpcCouponServiceServer) mustEmbedUnimplementedGrpcCouponServiceServer() {}
func (UnimplementedGrpcCouponServiceServer) testEmbeddedByValue()                           {}

// UnsafeGrpcCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcCouponServiceServer will
// result in compilation errors.
type UnsafeGrpcCouponServiceServer interface {
	mustEmbedUnimplementedGrpcCouponServiceServer()
}

func RegisterGrpcCouponServiceServer(s grpc.ServiceRegistrar, srv GrpcCouponServiceServer) {
	// If the following call pancis, it indicates UnimplementedGrpcCouponServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrpcCouponService_ServiceDesc, srv)
}

func _GrpcCouponService_GrpcGetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcGetCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcCouponServiceServer).GrpcGetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcCouponService_GrpcGetCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcCouponServiceServer).GrpcGetCoupon(ctx, req.(*GrpcGetCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcCouponService_ServiceDesc is the grpc.ServiceDesc for GrpcCouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcCouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcCouponService",
	HandlerType: (*GrpcCouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GrpcGetCoupon",
			Handler:    _GrpcCouponService_GrpcGetCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon.proto",
}
