// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcGetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcGetOrderReq) Reset() {
	*x = GrpcGetOrderReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcGetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGetOrderReq) ProtoMessage() {}

func (x *GrpcGetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGetOrderReq.ProtoReflect.Descriptor instead.
func (*GrpcGetOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcGetOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GrpcGetOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderName     string                 `protobuf:"bytes,2,opt,name=orderName,proto3" json:"orderName,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcGetOrderResp) Reset() {
	*x = GrpcGetOrderResp{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcGetOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGetOrderResp) ProtoMessage() {}

func (x *GrpcGetOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGetOrderResp.ProtoReflect.Descriptor instead.
func (*GrpcGetOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcGetOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GrpcGetOrderResp) GetOrderName() string {
	if x != nil {
		return x.OrderName
	}
	return ""
}

func (x *GrpcGetOrderResp) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\"+\n" +
	"\x0fGrpcGetOrderReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\"`\n" +
	"\x10GrpcGetOrderResp\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12\x1c\n" +
	"\torderName\x18\x02 \x01(\tR\torderName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price2G\n" +
	"\x10GrpcOrderService\x123\n" +
	"\fGrpcGetOrder\x12\x10.GrpcGetOrderReq\x1a\x11.GrpcGetOrderRespB\x0eZ\f./grpc/orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_proto_goTypes = []any{
	(*GrpcGetOrderReq)(nil),  // 0: GrpcGetOrderReq
	(*GrpcGetOrderResp)(nil), // 1: GrpcGetOrderResp
}
var file_order_proto_depIdxs = []int32{
	0, // 0: GrpcOrderService.GrpcGetOrder:input_type -> GrpcGetOrderReq
	1, // 1: GrpcOrderService.GrpcGetOrder:output_type -> GrpcGetOrderResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
