---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/15 17:21
--- origin_server_load_balance.lua
--- 回源服务器负载均衡


math.randomseed(os.time())

local OriginServer = {}
OriginServer.__index = OriginServer

-- weightedRandom 在所有有权重的服务器中进行加权随机
local function weightedRandom(weightServers)
    if #weightServers == 0 then
        return nil, "no servers len(weightServers) == 0"
    end

    -- 根据 weight 从大到小排序
    table.sort(weightServers, function(a, b)
        return a.Weight > b.Weight
    end)

    local totalWeight = 0
    for _, server in ipairs(weightServers) do
        if server.Weight > 0 then
            totalWeight = totalWeight + server.Weight
        end
    end

    if totalWeight == 0 then
        return nil, "no servers totalWeight == 0"
    end

    -- 随机数rnum区间范围 -> [0, totalWeight)
    local rnum = math.random(totalWeight) - 1

    local current = 0
    for _, server in ipairs(weightServers) do
        if server.Weight > 0 then
            current = current + server.Weight
            if rnum < current then
                return server, nil
            end
        end
    end

    -- 兜底，lua索引从1开始
    return weightServers[#weightServers], nil
end


originServerPollTab = {}
-- smoothWeightedRoundRobin平滑加权轮询
local function smoothWeightedRoundRobin(originServers)

    -- 根据 weight 从大到小排序
    table.sort(weightServers, function(a, b)
        return a.Weight > b.Weight
    end)

    local totalWeight = 0
    for _, server in ipairs(weightServers) do
        if server.Weight > 0 then
            totalWeight = totalWeight + server.Weight
            -- 初始化标记
            if originServerPollMap[server.Address] == nil then
                originServerPollMap[server.Address] = 0
            end
        end
    end

    if totalWeight == 0 then
        return nil, "no servers totalWeight == 0"
    end
    
    local selected = nil
    for _, s in ipairs(weightServers) do
        if s.weight and s.weight > 0 then
            originServerPollMap[server.Address] = originServerPollMap[server.Address] + server.weight

            if not selected or originServerPollMap[server.Address] > originServerPollMap[selected.Address] then
                selected = s
            end
            
        end
    end

    if not selected then
        return nil, "no server selected"
    end

    -- 轮询平滑
    originServerPollMap[selected.Address] = originServerPollMap[selected.Address] - selected.weight
    return selected, nil
end

-- selectServer：优先主节点（backup=false）
local function selectServer(originServers)
    if #originServers == 0 then
        return nil, "no servers len(originServers) == 0"
    end

    local primaryServers = {}
    local backupServers = {}

    for _, server in ipairs(originServers) do
        if server.Backup then
            table.insert(backupServers, server)
        else
            table.insert(primaryServers, server)
        end
    end

    -- 优先使用主服务器
    if #primaryServers > 0 then
        return weightedRandom(primaryServers)
    end

    print("primaryServers is null.")

    -- 再使用备用服务器
    if #backupServers > 0 then
        return weightedRandom(backupServers)
    end

    return nil, "no server found"
end

-- ======================
-- 测试代码（等价 Test111）
-- ======================
local servers = {
    { Address = "192.168.10.2", Port = 80, Weight = 3,  Backup = false },
    { Address = "192.168.10.3", Port = 80, Weight = 2,  Backup = false },
    { Address = "192.168.10.1", Port = 80, Weight = 5,  Backup = false },
    { Address = "192.168.10.5", Port = 80, Weight = 10, Backup = true },
}

local server, err = selectServer(servers)
if err then
    error(err)
end

print("selected:", server.Address, server.Port)



