---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/15 17:21
--- origin_server_load_balance.lua
--- 回源服务器负载均衡


local OriginServer = {}
OriginServer.__index = OriginServer

originServerPollMap = {}
-- smoothWeightedRoundRobin平滑加权轮询
local function smoothWeightedRoundRobin2(weightServers)

    -- 根据 weight 从大到小排序
    table.sort(weightServers, function(a, b)
        return a.Weight > b.Weight
    end)

    local totalWeight = 0
    for _, server in ipairs(weightServers) do
        if server.Weight > 0 then
            totalWeight = totalWeight + server.Weight
            -- 初始化标记
            if originServerPollMap[server.Address] == nil then
                originServerPollMap[server.Address] = 0
            end
        end
    end

    if totalWeight == 0 then
        return nil, "no servers totalWeight == 0"
    end
    
    local selected = nil
    for _, s in ipairs(weightServers) do
        if s.weight and s.weight > 0 then
            originServerPollMap[server.Address] = originServerPollMap[server.Address] + server.weight

            if not selected or originServerPollMap[server.Address] > originServerPollMap[selected.Address] then
                selected = s
            end
        end
    end

    if not selected then
        return nil, "no server selected"
    end

    -- 轮询平滑
    originServerPollMap[selected.Address] = originServerPollMap[selected.Address] - selected.weight
    return selected, nil
end

originServerPollMap = {}
local function smoothWeightedRoundRobin(weightServers)
    if not weightServers or #weightServers == 0 then
        return nil, "no servers"
    end

    local totalWeight = 0

    -- 计算 totalWeight，并初始化 currentWeight
    for _, s in ipairs(weightServers) do
        if s.Weight and s.Weight > 0 then
            totalWeight = totalWeight + s.Weight
            if originServerPollMap[s.Address] == nil then
                originServerPollMap[s.Address] = 0
            end
        end
    end

    if totalWeight == 0 then
        return nil, "total weight is zero"
    end

    local selected = nil

    -- 核心算法
    for _, s in ipairs(weightServers) do
        if s.Weight and s.Weight > 0 then
            originServerPollMap[s.Address] =
            originServerPollMap[s.Address] + s.Weight

            if not selected or
                    originServerPollMap[s.Address] >
                            originServerPollMap[selected.Address] then
                selected = s
            end
        end
    end

    if not selected then
        return nil, "no server selected"
    end

    -- 关键步骤：平滑
    originServerPollMap[selected.Address] =
    originServerPollMap[selected.Address] - totalWeight

    return selected, nil
end

-- selectServer：优先主节点（backup=false）
local function selectServer(originServers)
    if #originServers == 0 then
        return nil, "no servers len(originServers) == 0"
    end

    local primaryServers = {}
    local backupServers = {}

    for _, server in ipairs(originServers) do
        if server.Backup then
            table.insert(backupServers, server)
        else
            table.insert(primaryServers, server)
        end
    end

    -- 优先使用主服务器
    if #primaryServers > 0 then
        return smoothWeightedRoundRobin(primaryServers)
    end

    print("primaryServers is null.")

    -- 再使用备用服务器
    if #backupServers > 0 then
        return smoothWeightedRoundRobin(backupServers)
    end

    return nil, "no server found"
end

-- ======================
-- 测试代码（等价 Test111）
-- ======================
local servers = {
    { Address = "192.168.10.2", Port = 80, Weight = 3,  Backup = false },
    { Address = "192.168.10.3", Port = 80, Weight = 2,  Backup = false },
    { Address = "192.168.10.1", Port = 80, Weight = 5,  Backup = false },
    { Address = "192.168.10.5", Port = 80, Weight = 10, Backup = true },
}


local aaTab = {}
for i = 1, 50 do
    local s, err = selectServer(servers)
    if not s then
        print(err)
    else
        print(s.Address)
        aaTab[s.Address] = (aaTab[s.Address] or 0) + 1
    end
end

for addr, times in pairs(aaTab) do
    print("addr = "..addr..", times = "..times)
end


