// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"go_zero_20_db_redis/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// http://127.0.0.1:8090/redis/get
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/redis/get",
				Handler: redisApiHandler(serverCtx),
			},
		},
	)
}
