// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

import "time"

type OrderInfo struct {
	OrderId   int64   `orm:"column(order_id)"`   //订单id
	GoodsName string  `orm:"column(goods_name)"` //商品名称
	Price     float64 `orm:"column(price)"`      //商品名称
	Status    string    `orm:"column(status);size(1);null"`
	CreatedAt time.Time `orm:"column(created_at);type(datetime);auto_now_add"`
	UpdatedAt time.Time `orm:"column(updated_at);type(datetime);auto_now"`
}


// https://go-zero.dev/docs/tutorials/http/server/request-body
// go-zero的各种请求方式
//Json 请求参数
//Form 表单请求参数
//Json 请求参数
//Header 参数获取

// 详细请看：参数规则：：：https://go-zero.dev/docs/tutorials/api/parameter



//Json 请求参数
//对于 Json 参数请求，其接受来自 Post 请求方法 Content-Type 为 application/json 的请求参数，
//其写法是在结构体的 tag 中加上 json 关键字，
//在 tag 中写法是一个 k-v 结构，key 是固定值 json，value 是对应 json 的 key 值。
type InsertOrderInfoReq struct {
	GoodsName string  `json:"goodsName"` //商品名称
	Price     float64 `json:"price,range=(0:100]"`     //商品名称
	Type     float64 `json:"type,options=1|2|3|4|5"`     //商品名称
}


//header 参数获取，
//对于header 参数获取，其写法是在结构体的 tag 中加上 header 关键字，
//用于获取特定的请求头的值，其是一个 k-v格式， key 为固定值 header，value 为请求头的 key 值。
type UpdateOrderInfoReq struct {
	OrderId   int64   `json:"orderId"`   //订单id
	GoodsName string  `json:"goodsName"` //商品名称
	Price     float64 `json:"price"`     //商品名称
	Authorization string `header:"authorization"`
}


// Path 请求参数
//对于 Path 参数请求，其支持在路径上定义参数，其写法是在结构体的 tag 中加上 path 关键字，用于获取特定的路径参数，
//其是一个 k-v格式， key 为固定值 path，value 为路径参数的变量。
type DeleteOrderInfoReq struct {
	OrderId int64 `path:"orderId"` // 订单id ✅ 添加 path 标签
}

//Form 表单请求参数
//对于表单请求参数，go-zero 支持通过 form tag 来定义参数的名称，其支持 Content-Type 为 application/x-www-form-urlencoded 的请求参数，
//也支持 Get 方法的 query 参数，其写法是在结构体的 tag 中加上 form 关键字，
//在 tag 中的写法是一个 k-v 结构，key 是固定值 form，value 是对应 query 的 key 值。
type OrderInfoPageListReq struct {
	PageNum   int `form:"pageNum"`
	PageSize  int `form:"pageSize"`
	GoodsName string `form:"goodsName,optional,default="` //商品名称
}

type OrderInfoPageListResp struct {
	PageNum       int
	PageSize      int
	Total         int
	OrderInfoList []OrderInfoResp
}

type OrderInfoReq struct {
	OrderId int64 `form:"orderId"`
}

type OrderInfoResp struct {
	OrderId   int64  `json:"orderId"`   //订单id
	GoodsName string `json:"goodsName"` //商品名称
}


type SendSSEReq struct {
	Uuid string `form:"uuid,optional"`
	Content string `form:"content,optional,default=Hello"`
}