// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type UserInfoReq struct {
}

type UserInfoResp struct {
}

type UserInfoUpdateReq struct {
}

type UserInfoUpdateResp struct {
}

type UserLoginReq struct {
}

type UserLoginResp struct {
}
