// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/pay.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义一个为PayChargeRequest的消息类型
type PayChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayChargeRequest) Reset() {
	*x = PayChargeRequest{}
	mi := &file_proto_pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayChargeRequest) ProtoMessage() {}

func (x *PayChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayChargeRequest.ProtoReflect.Descriptor instead.
func (*PayChargeRequest) Descriptor() ([]byte, []int) {
	return file_proto_pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayChargeRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *PayChargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PayChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayChargeResponse) Reset() {
	*x = PayChargeResponse{}
	mi := &file_proto_pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayChargeResponse) ProtoMessage() {}

func (x *PayChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayChargeResponse.ProtoReflect.Descriptor instead.
func (*PayChargeResponse) Descriptor() ([]byte, []int) {
	return file_proto_pay_proto_rawDescGZIP(), []int{1}
}

func (x *PayChargeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PayQueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayQueryStatusRequest) Reset() {
	*x = PayQueryStatusRequest{}
	mi := &file_proto_pay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayQueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayQueryStatusRequest) ProtoMessage() {}

func (x *PayQueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayQueryStatusRequest.ProtoReflect.Descriptor instead.
func (*PayQueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_pay_proto_rawDescGZIP(), []int{2}
}

func (x *PayQueryStatusRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type PayQueryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayQueryStatusResponse) Reset() {
	*x = PayQueryStatusResponse{}
	mi := &file_proto_pay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayQueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayQueryStatusResponse) ProtoMessage() {}

func (x *PayQueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayQueryStatusResponse.ProtoReflect.Descriptor instead.
func (*PayQueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_pay_proto_rawDescGZIP(), []int{3}
}

func (x *PayQueryStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_pay_proto protoreflect.FileDescriptor

const file_proto_pay_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pay.proto\x12\x05proto\"B\n" +
	"\x10PayChargeRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"-\n" +
	"\x11PayChargeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x15PayQueryStatusRequest\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\"2\n" +
	"\x16PayQueryStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x96\x01\n" +
	"\vPay2Service\x12;\n" +
	"\x06Charge\x12\x17.proto.PayChargeRequest\x1a\x18.proto.PayChargeResponse\x12J\n" +
	"\vQueryStatus\x12\x1c.proto.PayQueryStatusRequest\x1a\x1d.proto.PayQueryStatusResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_pay_proto_rawDescOnce sync.Once
	file_proto_pay_proto_rawDescData []byte
)

func file_proto_pay_proto_rawDescGZIP() []byte {
	file_proto_pay_proto_rawDescOnce.Do(func() {
		file_proto_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pay_proto_rawDesc), len(file_proto_pay_proto_rawDesc)))
	})
	return file_proto_pay_proto_rawDescData
}

var file_proto_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pay_proto_goTypes = []any{
	(*PayChargeRequest)(nil),       // 0: proto.PayChargeRequest
	(*PayChargeResponse)(nil),      // 1: proto.PayChargeResponse
	(*PayQueryStatusRequest)(nil),  // 2: proto.PayQueryStatusRequest
	(*PayQueryStatusResponse)(nil), // 3: proto.PayQueryStatusResponse
}
var file_proto_pay_proto_depIdxs = []int32{
	0, // 0: proto.Pay2Service.Charge:input_type -> proto.PayChargeRequest
	2, // 1: proto.Pay2Service.QueryStatus:input_type -> proto.PayQueryStatusRequest
	1, // 2: proto.Pay2Service.Charge:output_type -> proto.PayChargeResponse
	3, // 3: proto.Pay2Service.QueryStatus:output_type -> proto.PayQueryStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pay_proto_init() }
func file_proto_pay_proto_init() {
	if File_proto_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pay_proto_rawDesc), len(file_proto_pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pay_proto_goTypes,
		DependencyIndexes: file_proto_pay_proto_depIdxs,
		MessageInfos:      file_proto_pay_proto_msgTypes,
	}.Build()
	File_proto_pay_proto = out.File
	file_proto_pay_proto_goTypes = nil
	file_proto_pay_proto_depIdxs = nil
}
