// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/pay.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pay2Service_Charge_FullMethodName      = "/proto.Pay2Service/Charge"
	Pay2Service_QueryStatus_FullMethodName = "/proto.Pay2Service/QueryStatus"
)

// Pay2ServiceClient is the client API for Pay2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义一个叫 Pay2Service 的grpc服务
type Pay2ServiceClient interface {
	Charge(ctx context.Context, in *PayChargeRequest, opts ...grpc.CallOption) (*PayChargeResponse, error)
	QueryStatus(ctx context.Context, in *PayQueryStatusRequest, opts ...grpc.CallOption) (*PayQueryStatusResponse, error)
}

type pay2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPay2ServiceClient(cc grpc.ClientConnInterface) Pay2ServiceClient {
	return &pay2ServiceClient{cc}
}

func (c *pay2ServiceClient) Charge(ctx context.Context, in *PayChargeRequest, opts ...grpc.CallOption) (*PayChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayChargeResponse)
	err := c.cc.Invoke(ctx, Pay2Service_Charge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pay2ServiceClient) QueryStatus(ctx context.Context, in *PayQueryStatusRequest, opts ...grpc.CallOption) (*PayQueryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayQueryStatusResponse)
	err := c.cc.Invoke(ctx, Pay2Service_QueryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Pay2ServiceServer is the server API for Pay2Service service.
// All implementations must embed UnimplementedPay2ServiceServer
// for forward compatibility.
//
// 定义一个叫 Pay2Service 的grpc服务
type Pay2ServiceServer interface {
	Charge(context.Context, *PayChargeRequest) (*PayChargeResponse, error)
	QueryStatus(context.Context, *PayQueryStatusRequest) (*PayQueryStatusResponse, error)
	mustEmbedUnimplementedPay2ServiceServer()
}

// UnimplementedPay2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPay2ServiceServer struct{}

func (UnimplementedPay2ServiceServer) Charge(context.Context, *PayChargeRequest) (*PayChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charge not implemented")
}
func (UnimplementedPay2ServiceServer) QueryStatus(context.Context, *PayQueryStatusRequest) (*PayQueryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStatus not implemented")
}
func (UnimplementedPay2ServiceServer) mustEmbedUnimplementedPay2ServiceServer() {}
func (UnimplementedPay2ServiceServer) testEmbeddedByValue()                     {}

// UnsafePay2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Pay2ServiceServer will
// result in compilation errors.
type UnsafePay2ServiceServer interface {
	mustEmbedUnimplementedPay2ServiceServer()
}

func RegisterPay2ServiceServer(s grpc.ServiceRegistrar, srv Pay2ServiceServer) {
	// If the following call pancis, it indicates UnimplementedPay2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pay2Service_ServiceDesc, srv)
}

func _Pay2Service_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pay2ServiceServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pay2Service_Charge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pay2ServiceServer).Charge(ctx, req.(*PayChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay2Service_QueryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayQueryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Pay2ServiceServer).QueryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pay2Service_QueryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Pay2ServiceServer).QueryStatus(ctx, req.(*PayQueryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pay2Service_ServiceDesc is the grpc.ServiceDesc for Pay2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pay2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Pay2Service",
	HandlerType: (*Pay2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _Pay2Service_Charge_Handler,
		},
		{
			MethodName: "QueryStatus",
			Handler:    _Pay2Service_QueryStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pay.proto",
}
