// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type InsertUserInfoReq struct {
	Username string `json:"username"` //用户名
	Name     string `json:"name"`     //名字
	Address  string `json:"address"`  //地址
	Age      int    `json:"age"`      //年龄
}

type UserInfoReq struct {
	UserId   int64  `form:"userId,optional"`   //用户id
	Username string `form:"username,optional"` //用户名
	Name     string `form:"name,optional"`     //名字
}

type UserInfoResp struct {
	UserId   int64  `json:"userId"`   //用户id
	Username string `json:"username"` //用户名
	Name     string `json:"name"`     //名字
	Address  string `json:"address"`  //地址
	Age      int    `json:"age"`      //年龄
}
