// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DelayQueueReq struct {
	Queue    string `form:"queue"`
	Router   string `form:"router"`
	Exchange string `form:"exchange"`
	Msg      string `form:"msg"`
}
