---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/4 09:50
---
---
---
---
print(111)
local cjson = require "cjson.safe"
print(222)
arg = {"q", "asac", 123, {"a", "s", 33}}
arg["aa"] = 666
print(cjson.encode(arg))

cjson.encode_empty_table_as_object()
print(cjson.encode({}))
cjson.encode_empty_table_as_object(false)
print(cjson.encode({}))



local s, err = cjson.encode({ a = function() end })
if not s then
    ngx.log(ngx.ERR, "encode failed: ", err)
else
    print(s)
end


print(333)


arg["das"] = 89089
print(arg["das"])




    local dict_name = "rate_limit"
    local dict = ngx.shared[dict_name]

    if not dict then
        ngx.log(ngx.ERR, "shared dict not found: ", dict_name)
        return nil, "shared dict not found"
    end

