---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxc20250729.
--- DateTime: 2025/12/4 10:26
---

--local cjson = require "cjson.safe"
--local cjson = require("cjson.safe")


local dict_name = "rate_limit"
local dict = ngx.shared[dict_name]

local tab = {}

tab["aa"] = 888

print(tab["aa"])

table.insert(tab, 999)

for k, v in pairs(tab) do
    print(k.." -> "..v)
end

