// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"grpc_coupon/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取优惠劵信息
				Method:  http.MethodGet,
				Path:    "/coupon/info",
				Handler: GetCouponHandler(serverCtx),
			},
			{
				// 新增优惠劵
				Method:  http.MethodPost,
				Path:    "/coupon/info",
				Handler: InsertCouponHandler(serverCtx),
			},
		},
	)
}
